<?php

// Plugin definition
$plugin = array(
  'title' => t('Homepage - 3 - 1 - 2 stacked'),
  'icon' => 'three_one_two_stacked.png',
  'theme' => 'three_one_two_stacked',
  'css' => 'three_one_two_stacked.css',
  'panels' => array(
    'top-left' => t('Top left'),
    'top-middle' => t('Top middle'),
    'top-right' => t('Top right'),
    'top' => t('Top'),
    'left' => t('Left side'),
    'right' => t('Right side'),
    'bottom' => t('Bottom')
  ),
);
